# This workflow has muliple jobs, one for testing and one for deployment.
# this workflow runs in sequence
name: Deploy Project
# to hva multiple trigger events, we can use the on: keyword
# to specify multiple events
# in this case, we are using push event
# to trigger the workflow
# if I wanted to add another event, I can do so by adding a comma like [push, pull_request]
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        #   This uses an existing github action called checkout to get code to repo
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm test

  deploy:
    # This job depends on the test job. It will only run if the test job is successful.
    # This is how we can run jobs in sequence
    # deploy will run only if test job is successful
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        #   This uses an existing github action called checkout to get code to repo
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy Project
        run: echo "Deploying project..."
