name: Output Context
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub Context
        # This echoes the GitHub context to the console
        # This is useful for debugging and understanding the context
        # that is available to the workflow
        run: echo "${{ toJson(github) }}"
